import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  checkpoint,
  createReport,
  finish,
  gitRevision,
  loadManifest,
  parseRunnerArguments,
  sha256,
} from "./report.mjs";

function parseArguments(argv) {
  const split = argv.indexOf("--");
  if (split === -1) throw new Error("expected -- before runner arguments");
  const adapterArguments = argv.slice(0, split);
  const options = parseRunnerArguments(argv.slice(split + 1));
  const adapter = { binary: undefined, runtime: undefined };
  for (let index = 0; index < adapterArguments.length; index += 1) {
    const argument = adapterArguments[index];
    if (argument === "--binary") adapter.binary = resolve(adapterArguments[++index]);
    else if (argument === "--runtime") adapter.runtime = adapterArguments[++index];
    else throw new Error(`unknown adapter argument: ${argument}`);
  }
  if (!adapter.binary || adapter.runtime !== "cli") {
    throw new Error("--runtime cli and --binary are required");
  }
  return { adapter, options };
}

function rssKb(pid) {
  try {
    const status = readFileSync(`/proc/${pid}/status`, "utf8");
    const match = /^VmRSS:\s+(\d+)\s+kB$/m.exec(status);
    return match ? Number(match[1]) : undefined;
  } catch {
    return undefined;
  }
}

function runProcess(binary, args, environment) {
  return new Promise((resolveRun) => {
    const child = spawn(binary, args, { env: environment, stdio: ["ignore", "pipe", "pipe"] });
    const hash = createHash("sha256");
    let outputBytes = 0;
    let peakRssKb = rssKb(child.pid);
    let stderr = "";
    const started = process.hrtime.bigint();
    const sampler = setInterval(() => {
      const current = rssKb(child.pid);
      if (current !== undefined) peakRssKb = Math.max(peakRssKb ?? 0, current);
    }, 50);

    child.stdout.on("data", (chunk) => {
      outputBytes += chunk.length;
      hash.update(chunk);
    });
    child.stderr.on("data", (chunk) => {
      if (stderr.length < 131_072) stderr += chunk.toString();
    });
    child.on("error", (error) => {
      clearInterval(sampler);
      resolveRun({ status: "error", error: String(error), outputBytes, peakRssKb });
    });
    child.on("close", (code, signal) => {
      clearInterval(sampler);
      const wallMs = Number((process.hrtime.bigint() - started) / 1_000_000n);
      resolveRun({
        status: code === 0 ? "ok" : "error",
        code,
        signal,
        stderr: stderr.trim() || undefined,
        wallMs,
        outputBytes,
        outputSha256: hash.digest("hex"),
        memory: { peakRssKb },
      });
    });
  });
}

async function preload(binary, languages, environment) {
  const result = await runProcess(binary, ["languages", "cache", ...languages], environment);
  if (result.status !== "ok") throw new Error(`CLI parser preload failed: ${result.stderr}`);
  return { wallMs: result.wallMs, memory: result.memory };
}

const { adapter, options } = parseArguments(process.argv.slice(2));
const manifest = await loadManifest(options.manifest);
const environment = { ...process.env };
const languages = [...new Set(manifest.cases.map(({ language }) => language))].sort();
const report = createReport(
  {
    id: "cli",
    implementation: "lumis-wasm-runtime-process",
    node: process.version,
    platform: process.platform,
    architecture: process.arch,
    gitRevision: await gitRevision(),
  },
  manifest,
  options,
);
await checkpoint(options, report, undefined);
report.preload = await preload(adapter.binary, languages, environment);
await checkpoint(options, report, undefined);

for (const testCase of manifest.cases) {
  await checkpoint(options, report, testCase.id);
  const source = await readFile(resolve(testCase.generatedPath));
  if (source.length !== testCase.generated.bytes || sha256(source) !== testCase.sourceSha256) {
    throw new Error(`generated bytes changed for ${testCase.id}`);
  }

  const iterations = [];
  for (let iteration = 1; iteration <= options.iterations; iteration += 1) {
    const measured = await runProcess(
      adapter.binary,
      ["highlight", testCase.generatedPath, "--language", testCase.language, "--formatter", "html-linked"],
      environment,
    );
    iterations.push({ iteration, ...measured });
  }
  const successes = iterations.filter(({ status }) => status === "ok");
  const outputBytes = Math.max(0, ...successes.map((result) => result.outputBytes));
  const hashes = new Set(successes.map(({ outputSha256 }) => outputSha256));
  const result = {
    id: testCase.id,
    profile: testCase.profile,
    language: testCase.language,
    status: successes.length === iterations.length ? "ok" : "error",
    generated: testCase.generated,
    sourceSha256: testCase.sourceSha256,
    origins: testCase.origins,
    deterministic: hashes.size <= 1,
    outputBytes,
    outputAmplification: outputBytes / Math.max(source.length, 1),
    iterations,
  };
  report.results.push(result);
  process.stdout.write(
    `${result.id}: ${Math.max(...iterations.map(({ wallMs }) => wallMs ?? 0))} ms, ` +
      `${source.length} source bytes, ${outputBytes} output bytes\n`,
  );
  await checkpoint(options, report, undefined);
}

await finish(options, report);
