// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from "../src/types.js";
import { lazy } from "../src/bundle-helpers.js";

export const bundledLanguages: LanguageBundle = {
  asm: lazy("asm", ["assembly"], () => import("../langs/asm.js")),
  bash: lazy(
    "bash",
    ["console", "sh", "sh-session", "shell", "shell-session", "terminal"],
    () => import("../langs/bash.js"),
  ),
  c: lazy("c", [], () => import("../langs/c.js")),
  cmake: lazy("cmake", [], () => import("../langs/cmake.js")),
  cpp: lazy("cpp", ["c++"], () => import("../langs/cpp.js")),
  go: lazy("go", [], () => import("../langs/go.js")),
  llvm: lazy("llvm", [], () => import("../langs/llvm.js")),
  make: lazy("make", [], () => import("../langs/make.js")),
  rust: lazy("rust", [], () => import("../langs/rust.js")),
  wat: lazy("wat", ["wasm", "webassembly"], () => import("../langs/wat.js")),
  zig: lazy("zig", [], () => import("../langs/zig.js")),
  zsh: lazy("zsh", [], () => import("../langs/zsh.js")),
  plaintext: lazy("plaintext", ["text", "txt", "plain"], () => import("../langs/plaintext.js")),
};
