// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from "../src/types.js";
import { lazy } from "../src/bundle-helpers.js";

export const bundledLanguages: LanguageBundle = {
  angular: lazy("angular", [], () => import("../langs/angular.js")),
  astro: lazy("astro", [], () => import("../langs/astro.js")),
  dart: lazy("dart", [], () => import("../langs/dart.js")),
  eex: lazy("eex", ["leex"], () => import("../langs/eex.js")),
  ejs: lazy("ejs", [], () => import("../langs/ejs.js")),
  elm: lazy("elm", [], () => import("../langs/elm.js")),
  erb: lazy("erb", [], () => import("../langs/erb.js")),
  glimmer: lazy("glimmer", ["ember", "handlebars"], () => import("../langs/glimmer.js")),
  graphql: lazy("graphql", ["gql"], () => import("../langs/graphql.js")),
  heex: lazy("heex", [], () => import("../langs/heex.js")),
  markdown: lazy("markdown", [], () => import("../langs/markdown.js")),
  markdown_inline: lazy("markdown_inline", [], () => import("../langs/markdown_inline.js")),
  mdx: lazy("mdx", [], () => import("../langs/mdx.js")),
  php: lazy("php", [], () => import("../langs/php.js")),
  prisma: lazy("prisma", [], () => import("../langs/prisma.js")),
  scss: lazy("scss", [], () => import("../langs/scss.js")),
  surface: lazy("surface", [], () => import("../langs/surface.js")),
  svelte: lazy("svelte", [], () => import("../langs/svelte.js")),
  vue: lazy("vue", [], () => import("../langs/vue.js")),
  xml: lazy("xml", [], () => import("../langs/xml.js")),
  plaintext: lazy("plaintext", ["text", "txt", "plain"], () => import("../langs/plaintext.js")),
};
