// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from "../src/types.js";
import { lazy } from "../src/bundle-helpers.js";

export const bundledLanguages: LanguageBundle = {
  css: lazy("css", [], () => import("../langs/css.js")),
  html: lazy("html", [], () => import("../langs/html.js")),
  javascript: lazy("javascript", ["js", "jsx"], () => import("../langs/javascript.js")),
  json: lazy("json", ["jsonc", "jsonld"], () => import("../langs/json.js")),
  tsx: lazy("tsx", [], () => import("../langs/tsx.js")),
  typescript: lazy("typescript", ["ts"], () => import("../langs/typescript.js")),
  plaintext: lazy("plaintext", ["text", "txt", "plain"], () => import("../langs/plaintext.js")),
};
