[package]
name = "lumis-wasm-runtime"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "Shared Tree-sitter highlighting runtime for Lumis"

[features]
default = ["wasm"]
wasm = ["dep:wasmtime", "dep:ureq", "dep:typed-arena", "tree-sitter/wasm"]

[dependencies]
typed-arena = { version = "2", optional = true }
ureq = { version = "3", optional = true }
etcetera = "0.11"
lumis-core = { path = "../lumis-core", version = "2.5.0", default-features = false }
streaming-iterator = "0.1"
thiserror = "2"
tree-sitter = "^0.26.9"
wasmtime = { version = "36", default-features = false, features = ["cache", "cranelift", "runtime", "std"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
semver = "1"
sha2 = "0.11"
tempfile = "3"
wasmparser = "0.258"

[dev-dependencies]
tree-sitter-json = "0.24.8"

[lints]
workspace = true
