import type { HtmlAttrs } from "../types.js";

/**
 * Union two class lists, in order, without repeats.
 *
 * @internal
 */
export function mergeClasses(generated: HtmlAttrs[string], authored: HtmlAttrs[string]): string {
  const classes = [generated, authored]
    .flatMap((value) =>
      typeof value === "string" || typeof value === "number"
        ? String(value)
            .split(/[\t\n\f\r ]+/)
            .filter(Boolean)
        : [],
    )
    .filter((value, index, all) => all.indexOf(value) === index);

  return classes.join(" ");
}

function appendStyles(generated: HtmlAttrs[string], authored: HtmlAttrs[string]): string {
  const generatedStyle =
    typeof generated === "string" || typeof generated === "number" ? String(generated).trim() : "";
  const authoredStyle =
    typeof authored === "string" || typeof authored === "number" ? String(authored).trim() : "";

  if (generatedStyle.length === 0) return authoredStyle;
  if (authoredStyle.length === 0) return generatedStyle;
  return `${generatedStyle.replace(/;?$/, ";")} ${authoredStyle}`;
}

function matchingAttrName(attrs: HtmlAttrs, name: string): string | undefined {
  return Object.keys(attrs).find((candidate) => candidate.toLowerCase() === name.toLowerCase());
}

/**
 * What a `false`, `null` or `undefined` value does.
 *
 * `drop` is for merging over the attributes a formatter generated: the removal
 * has found its target and nothing needs to carry it further. `keep` is for
 * stacking one authored set on another, where the attribute to remove is
 * generated by a formatter that has not run yet, so the request has to survive
 * until it does. A kept `false` renders as nothing either way.
 */
type Removal = "drop" | "keep";

function replaceMergedAttr(
  merged: HtmlAttrs,
  existingName: string | undefined,
  targetName: string,
  value: HtmlAttrs[string],
  removal: Removal,
): void {
  if (value == null || value === false) {
    if (existingName) delete merged[existingName];
    if (removal === "keep") merged[targetName] = false;
    return;
  }

  merged[targetName] = value;
}

function mergeAuthoredAttr(
  merged: HtmlAttrs,
  authoredName: string,
  value: HtmlAttrs[string],
  removal: Removal,
): void {
  const existingName = matchingAttrName(merged, authoredName);
  const targetName = existingName ?? authoredName;

  switch (authoredName.toLowerCase()) {
    case "class": {
      const className = mergeClasses(merged[targetName], value);
      if (className.length > 0) merged[targetName] = className;
      return;
    }
    case "style": {
      const style = appendStyles(merged[targetName], value);
      if (style.length > 0) merged[targetName] = style;
      return;
    }
    default:
      replaceMergedAttr(merged, existingName, targetName, value, removal);
  }
}

/**
 * Layer `authored` over `generated`: `class` unions, `style` appends, and every
 * other name replaces. A `false`, `null` or `undefined` value removes the
 * attribute, which is how a caller drops a `tabindex` Lumis would generate.
 *
 * The built-in formatters merge their `preAttrs` and `codeAttrs` through this,
 * and {@link withAttrs} layers a second set on top of those, so the rule is the
 * same however many times it is applied.
 *
 * @internal
 */
export function mergeAttrs(generated: HtmlAttrs, authored: HtmlAttrs | undefined): HtmlAttrs {
  const merged = { ...generated };
  if (!authored) return merged;

  for (const [authoredName, value] of Object.entries(authored)) {
    mergeAuthoredAttr(merged, authoredName, value, "drop");
  }

  return merged;
}

/**
 * Stack one authored attribute set on another, by the same rules, before
 * either has met a formatter's generated attributes.
 *
 * Unlike {@link mergeAttrs} this keeps a `false`, because the attribute it
 * removes does not exist yet: `withAttrs(f, {codeAttrs: {tabindex: false}})`
 * has to still be asking for that when the formatter writes its `tabindex`.
 *
 * @internal
 */
export function layerAttrs(
  base: HtmlAttrs | undefined,
  extra: HtmlAttrs | undefined,
): HtmlAttrs | undefined {
  if (!base) return extra;
  if (!extra) return base;

  const merged = { ...base };
  for (const [name, value] of Object.entries(extra)) {
    mergeAuthoredAttr(merged, name, value, "keep");
  }

  return merged;
}
