import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createHighlighter, runtimeKind } from "../dist/index.js";
import { htmlLinked } from "../dist/formatters.js";
import {
  checkpoint,
  createReport,
  determinism,
  finish,
  gitRevision,
  loadManifest,
  parseRunnerArguments,
  sha256,
} from "../../../../stress-test/report.mjs";

function memorySnapshot() {
  const memory = process.memoryUsage();
  const resources = process.resourceUsage();
  return {
    rssBytes: memory.rss,
    heapUsedBytes: memory.heapUsed,
    externalBytes: memory.external,
    maxRssKb: resources.maxRSS,
  };
}

function measure(iteration, render) {
  const before = memorySnapshot();
  const started = process.hrtime.bigint();
  let output;
  try {
    output = render();
  } catch (error) {
    return {
      iteration,
      status: "error",
      error: String(error),
      wallMs: Number((process.hrtime.bigint() - started) / 1_000_000n),
      memory: { before, after: memorySnapshot() },
    };
  }
  const wallMs = Number((process.hrtime.bigint() - started) / 1_000_000n);
  const after = memorySnapshot();
  return {
    iteration,
    status: "ok",
    wallMs,
    outputBytes: Buffer.byteLength(output),
    outputSha256: sha256(output),
    memory: { before, after },
  };
}

const options = parseRunnerArguments(process.argv.slice(2));
const manifest = await loadManifest(options.manifest);
const expectedRuntime = process.env.LUMIS_TEST_RUNTIME;
const actualRuntime = runtimeKind();
if (expectedRuntime && actualRuntime !== expectedRuntime) {
  throw new Error(`requested ${expectedRuntime} runtime, loaded ${actualRuntime}`);
}

const languagesById = new Map();
/** @type {Set<string>} */
const languageIds = new Set(manifest.cases.map((testCase) => String(testCase.language)));
for (const id of languageIds) {
  languagesById.set(id, (await import(`../dist/langs/${id}.js`)).default);
}

const preloadStarted = process.hrtime.bigint();
const highlighter = await createHighlighter({ languages: [...languagesById.values()] });
const preload = {
  wallMs: Number((process.hrtime.bigint() - preloadStarted) / 1_000_000n),
  memory: memorySnapshot(),
};
const runtimeId = actualRuntime === "native" ? "javascript-native" : "javascript-wasm";
const report = createReport(
  {
    id: runtimeId,
    implementation: actualRuntime === "native" ? "napi-wasmtime" : "web-tree-sitter-node",
    node: process.version,
    platform: process.platform,
    architecture: process.arch,
    gitRevision: await gitRevision(),
  },
  manifest,
  options,
);
report.preload = preload;
await checkpoint(options, report, undefined);

for (const testCase of manifest.cases) {
  await checkpoint(options, report, testCase.id);
  const source = await readFile(resolve(testCase.generatedPath), "utf8");
  if (
    Buffer.byteLength(source) !== testCase.generated.bytes ||
    sha256(source) !== testCase.sourceSha256
  ) {
    throw new Error(`generated bytes changed for ${testCase.id}`);
  }

  const language = languagesById.get(testCase.language);
  const iterations = [];
  for (let iteration = 1; iteration <= options.iterations; iteration += 1) {
    iterations.push(
      measure(iteration, () => highlighter.highlight(source, htmlLinked({ language }))),
    );
  }
  const successes = iterations.filter(({ status }) => status === "ok");
  const outputBytes = Math.max(0, ...successes.map((result) => result.outputBytes));
  const result = {
    id: testCase.id,
    profile: testCase.profile,
    language: testCase.language,
    status: successes.length === iterations.length ? "ok" : "error",
    generated: testCase.generated,
    sourceSha256: testCase.sourceSha256,
    origins: testCase.origins,
    deterministic: determinism(successes.map(({ outputSha256 }) => outputSha256)),
    outputBytes,
    outputAmplification: outputBytes / Math.max(Buffer.byteLength(source), 1),
    iterations,
  };
  report.results.push(result);
  process.stdout.write(
    `${result.id}: ${result.status}, ${Math.max(...iterations.map(({ wallMs }) => wallMs))} ms, ` +
      `${testCase.generated.bytes} source bytes, ${outputBytes} output bytes\n`,
  );
  await checkpoint(options, report, undefined);
}

await finish(options, report);
