[package]
name = "lumis-cli"
version = "0.5.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "Syntax Highlighter CLI powered by Tree-sitter and Neovim themes"
keywords = ["lumis", "syntax-highlighter", "tree-sitter", "neovim", "cli"]
categories = ["command-line-utilities", "text-processing"]
include = [
  "/src/",
  "/themes/",
  "/build.rs",
  "/formatter-options.json",
  "/CHANGELOG.md",
  "/LICENSE",
]

[[bin]]
name = "lumis"
path = "src/main.rs"
doc = false

[dependencies]
lumis-core = { path = "../lumis-core", version = "2.5.0", features = ["all-languages"] }
lumis-wasm-runtime = { path = "../lumis-wasm-runtime", version = "0.2.1" }
tree-sitter = { version = "^0.26.9", features = ["wasm"] }
wasmtime = { version = "36", default-features = false, features = ["cache", "cranelift", "runtime", "std"] }
streaming-iterator = "0.1"
thiserror = "2"
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"
etcetera = "0.11"
tempfile = "3"
terminal_size = "0.4"
terminal-colorsaurus = "1.0.3"

[build-dependencies]
serde_json = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[lints]
workspace = true
