import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "installation",
    "architecture",
    {
      type: "category",
      label: "Operations",
      items: ["operations/warm-up"],
    },
    {
      type: "category",
      label: "Usage",
      items: [
        "usage/highlight",
        "usage/rust-advanced",
        "usage/javascript-runtime",
        "usage/elixir-integration",
        "usage/java",
        "usage/cli-highlight",
      ],
    },
    {
      type: "category",
      label: "Formatters",
      items: [
        "usage/formatters",
        "usage/formatters/html-inline",
        "usage/formatters/html-linked",
        "usage/formatters/html-multi-themes",
        "usage/formatters/terminal",
        "usage/formatters/bbcode",
        "usage/custom-formatters",
        "usage/annotations",
      ],
    },
    {
      type: "category",
      label: "Themes",
      items: ["usage/themes", "usage/css-theme-files", "usage/css-builder"],
    },
    {
      type: "category",
      label: "Integrations",
      items: [
        "integrations/react",
        "integrations/rehype-lumis",
        "integrations/markdown-it",
        "integrations/vitepress",
        "integrations/mdx",
        "integrations/nextjs",
        "integrations/astro",
        "integrations/unified-rehype",
        "integrations/react-markdown",
        "integrations/ratatui",
        "integrations/nimble-publisher",
        "integrations/tableau",
        "integrations/docusaurus",
        "integrations/nuxt",
      ],
    },
    {
      type: "category",
      label: "Recipes",
      items: [
        "recipes/index",
        "recipes/minimal-html",
        "recipes/auto-detect-language",
        "recipes/linked-html-css-theme-file",
        "recipes/multi-theme-html",
        "recipes/terminal-output",
        "recipes/wrap-output-with-custom-html",
        "recipes/custom-theme-from-json",
        "recipes/injected-languages-html-css-js",
        "recipes/phoenix-liveview-rendering",
        "recipes/stream-output-to-a-file-rust",
        "recipes/generate-css-from-a-theme-rust",
        "recipes/list-languages-and-themes",
        "recipes/generate-theme-from-neovim-colorscheme",
        "recipes/repeated-highlighting-javascript",
        "recipes/browser-cdn",
        "recipes/local-wasm-bundle",
        "recipes/light-dark",
        "recipes/file-title-copy",
        "usage/line-highlighting",
      ],
    },
    {
      type: "category",
      label: "CLI",
      items: ["cli/commands", "usage/cli-behavior"],
    },
    {
      type: "category",
      label: "Advanced",
      items: ["usage/wasm-and-cdn"],
    },
    {
      type: "category",
      label: "Reference",
      items: ["reference/languages", "reference/themes"],
    },
  ],
};

export default sidebars;
