/**
 * Generates JavaScript language metadata from languages.toml.
 *
 * Parser bytes, queries, integrity metadata, and exact versions belong to the
 * independently released @lumis-sh/wasm-* packages, not the runtimes.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { parse as parseToml } from "smol-toml";
import { parseLanguagesToml, type LanguagesToml } from "./languages-toml.js";

const WORKSPACE_ROOT = path.resolve(import.meta.dirname, "../../../..");
const OUT_DIR = path.resolve(import.meta.dirname, "../langs");
const GENERATED_DIR = path.resolve(import.meta.dirname, "../src/generated");
const BUNDLES_DIR = path.resolve(import.meta.dirname, "../bundles");

const LANGUAGES_TOML = path.join(WORKSPACE_ROOT, "languages.toml");
const CATALOG_RS = path.join(WORKSPACE_ROOT, "crates/lumis-wasm-runtime/src/catalog.rs");

function readLanguagesToml(): LanguagesToml {
  const text = fs.readFileSync(LANGUAGES_TOML, "utf-8");
  return parseLanguagesToml(parseToml(text));
}

// `mise run langs-gen-catalog` derives this from the Tree-sitter series pinned in
// mise.toml and writes it into the generated Rust catalog. Reading it back keeps
// one implementation rather than a second pin parser that could disagree about
// which series a runtime supports.
function languagePackageVersionRange(): string {
  const source = fs.readFileSync(CATALOG_RS, "utf-8");
  const range = /package_version_range:\s*"([^"]+)"/.exec(source)?.[1];
  if (!range) {
    throw new Error(
      `no package version range found in ${CATALOG_RS}; run mise run langs-gen-catalog`,
    );
  }
  return range;
}

function normalizeShebangCommand(command: string): string {
  return command.toLowerCase().replace(/\d+(?:\.\d+)*$/, "");
}

interface LanguageEntry {
  id: string;
  name: string;
  aliases: string[];
  extensions: string[];
  globs: string[];
  emacsModes: string[];
  shebangs: string[];
}

function writeLanguageFiles(config: LanguagesToml, plaintextAliases: string[]): void {
  const expectedLanguageIds = new Set([...Object.keys(config.parsers), "plaintext"]);

  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const entry of fs.readdirSync(OUT_DIR)) {
    if (!entry.endsWith(".ts")) continue;
    const id = path.parse(entry).name;
    if (expectedLanguageIds.has(id)) continue;
    fs.unlinkSync(path.join(OUT_DIR, entry));
    console.log(`  removed stale language: langs/${entry}`);
  }

  for (const [id, entry] of Object.entries(config.parsers)) {
    const wasmName = entry.wasm_name ?? `tree-sitter-${id}`;
    const packageName = `@lumis-sh/wasm-${wasmName.replace(/^tree-sitter-/, "")}`;
    const aliases = entry.aliases ?? [];

    const module = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguagePackageHandle } from '../src/types.js'

const language: LanguagePackageHandle = {
  id: ${JSON.stringify(id)},
  aliases: ${JSON.stringify(aliases)},
  packageName: ${JSON.stringify(packageName)},
}

export default language
`;

    fs.writeFileSync(path.join(OUT_DIR, `${id}.ts`), module);
    console.log(`  ${id}: langs/${id}.ts`);
  }

  const plaintextModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { PlaintextLanguage } from '../src/types.js'

const language: PlaintextLanguage = {
  id: "plaintext",
  aliases: ${JSON.stringify(plaintextAliases)},
}

export default language
`;
  fs.writeFileSync(path.join(OUT_DIR, "plaintext.ts"), plaintextModule);
  console.log(`  plaintext: langs/plaintext.ts`);
}

function collectLanguageEntries(
  config: LanguagesToml,
  plaintextAliases: string[],
): LanguageEntry[] {
  const languageEntries: LanguageEntry[] = [];

  for (const [id, entry] of Object.entries(config.parsers)) {
    const aliases = entry.aliases ?? [];
    const variant = entry.variant ?? titlecase(id);
    const name = entry.display_name ?? variant;
    const globs = entry.globs ?? [];
    const extensions = globs.filter((glob) => glob.startsWith("*."));
    const emacsModes = entry.emacs ?? [];
    const shebangs = entry.shebang ?? [];

    languageEntries.push({ id, name, aliases, extensions, globs, emacsModes, shebangs });
  }

  languageEntries.push({
    id: "plaintext",
    name: "Plain Text",
    aliases: plaintextAliases,
    extensions: [],
    globs: [],
    emacsModes: ["fundamental", "text"],
    shebangs: [],
  });
  languageEntries.sort((left, right) => (left.id < right.id ? -1 : left.id > right.id ? 1 : 0));
  return languageEntries;
}

function writeLanguageMetadata(languageEntries: LanguageEntry[], versionRange: string): void {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  fs.rmSync(path.join(GENERATED_DIR, "package-versions.ts"), { force: true });
  const packageVersionRangeModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
// Mirrors \`catalog::LANGUAGE_PACKAGE_VERSION_RANGE\` in crates/lumis-wasm-runtime.
export const LANGUAGE_PACKAGE_VERSION_RANGE = ${JSON.stringify(versionRange)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "package-version-range.ts"), packageVersionRangeModule);
  console.log(`  package version range: src/generated/package-version-range.ts`);

  const languageMetaModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageInfo } from '../types.js'

export const LANGUAGES: LanguageInfo[] = ${JSON.stringify(languageEntries, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "languages-meta.ts"), languageMetaModule);
  console.log(`  languages metadata: src/generated/languages-meta.ts`);

  const exactLanguageMap: Record<string, string> = {};
  const emacsModeMap: Record<string, string> = {};
  const shebangMap: Record<string, string> = {};
  const globMatchers: Array<{ id: string; glob: string }> = [];

  for (const language of languageEntries) {
    exactLanguageMap[language.id.toLowerCase()] = language.id;

    for (const alias of language.aliases) {
      exactLanguageMap[alias.toLowerCase()] = language.id;
    }

    for (const mode of language.emacsModes) {
      emacsModeMap[mode.toLowerCase()] = language.id;
    }

    for (const shebang of language.shebangs) {
      shebangMap[normalizeShebangCommand(shebang)] = language.id;
    }

    for (const glob of language.globs) {
      globMatchers.push({ id: language.id, glob: glob.toLowerCase() });
    }
  }

  const languageDetectionModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
export const EXACT_LANGUAGE_MAP: Record<string, string> = ${JSON.stringify(exactLanguageMap, null, 2)}

export const EMACS_MODE_MAP: Record<string, string> = ${JSON.stringify(emacsModeMap, null, 2)}

export const SHEBANG_MAP: Record<string, string> = ${JSON.stringify(shebangMap, null, 2)}

export const GLOB_MATCHERS: Array<{ id: string; glob: string }> = ${JSON.stringify(globMatchers, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "language-detection.ts"), languageDetectionModule);
  console.log(`  language detection: src/generated/language-detection.ts`);
}

function writeLanguageLoaders(config: LanguagesToml): void {
  const languageLoaderEntries = [...Object.keys(config.parsers), "plaintext"]
    .map((id) => `  ${JSON.stringify(id)}: () => import('../../langs/${id}.js'),`)
    .join("\n");

  const languageLoadersModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { Language } from '../types.js'

export const LANGUAGE_LOADERS: Record<string, () => Promise<{ default: Language }>> = {
${languageLoaderEntries}
}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "language-loaders.ts"), languageLoadersModule);
  console.log(`  language loaders: src/generated/language-loaders.ts`);

  // Every parser package, for asking which of them a project installed. Not
  // derivable from a language id — `mdx` comes from `@lumis-sh/wasm-markdown`,
  // and `ejs` and `erb` share `@lumis-sh/wasm-embedded-template`.
  const packageNames = [
    ...new Set(
      Object.entries(config.parsers).map(
        ([id, entry]) =>
          `@lumis-sh/wasm-${(entry.wasm_name ?? `tree-sitter-${id}`).replace(/^tree-sitter-/, "")}`,
      ),
    ),
  ].sort();

  const packageNamesModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.

export const LANGUAGE_PACKAGE_NAMES: string[] = ${JSON.stringify(packageNames, undefined, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "language-packages.ts"), packageNamesModule);
  console.log(`  language packages: src/generated/language-packages.ts`);
}

function writeThemeMetadata(): void {
  const THEMES_SRC = path.join(WORKSPACE_ROOT, "themes");
  const themeEntries: { name: string; appearance: string }[] = [];

  for (const file of fs
    .readdirSync(THEMES_SRC)
    .filter((f) => f.endsWith(".json"))
    .sort()) {
    const json = fs.readFileSync(path.join(THEMES_SRC, file), "utf-8");
    const data = JSON.parse(json);
    if (data.name && data.appearance) {
      themeEntries.push({ name: data.name, appearance: data.appearance });
    }
  }

  const themeMetaModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { ThemeInfo } from '../types.js'

export const THEMES: ThemeInfo[] = ${JSON.stringify(themeEntries, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "themes-meta.ts"), themeMetaModule);
  console.log(`  themes metadata: src/generated/themes-meta.ts`);
}

function writeBundles(config: LanguagesToml, plaintextAliases: string[]): void {
  fs.mkdirSync(BUNDLES_DIR, { recursive: true });

  const allParserIds = Object.keys(config.parsers);

  // Bundle membership as data, so `loadLanguages` can expand `bundle-web`
  // without importing every bundle's lazy language modules.
  const bundleMembers: Record<string, string[]> = {};
  for (const [bundleName, bundleEntry] of Object.entries(config.bundles ?? {})) {
    bundleMembers[bundleName] =
      bundleEntry.parsers === "all"
        ? allParserIds.filter((id) => !bundleEntry.exclude?.includes(id))
        : [...bundleEntry.parsers];
  }

  const bundleMetaModule = `// Auto-generated by scripts/build-langs.ts — do not edit manually.
export const BUNDLES: Record<string, string[]> = ${JSON.stringify(bundleMembers, null, 2)}
`;
  fs.writeFileSync(path.join(GENERATED_DIR, "bundles-meta.ts"), bundleMetaModule);
  console.log(`  bundles metadata: src/generated/bundles-meta.ts`);

  removeStaleBundles(new Set(Object.keys(config.bundles ?? {})));

  for (const [bundleName, bundleEntry] of Object.entries(config.bundles ?? {})) {
    const parserIds =
      bundleEntry.parsers === "all"
        ? allParserIds.filter((id) => !bundleEntry.exclude?.includes(id))
        : bundleEntry.parsers;
    const allIds = bundleLanguageIds(parserIds);

    fs.writeFileSync(
      path.join(BUNDLES_DIR, `${bundleName}.ts`),
      bundleModule(allIds, bundleAliases(config, parserIds, plaintextAliases)),
    );
    console.log(`  bundle ${bundleName}: bundles/${bundleName}.ts (${allIds.length} languages)`);
  }
}

function removeStaleBundles(expectedBundles: Set<string>): void {
  for (const entry of fs.readdirSync(BUNDLES_DIR)) {
    if (!entry.endsWith(".ts")) continue;

    const bundleName = path.parse(entry).name;
    if (expectedBundles.has(bundleName)) continue;

    fs.unlinkSync(path.join(BUNDLES_DIR, entry));
    console.log(`  removed stale bundle: bundles/${entry}`);
  }
}

// Plaintext needs no parser, so it has no `languages.toml` entry and gets its
// aliases assigned after the loop. Assigning rather than defaulting covers a
// bundle that names plaintext explicitly, which the schema allows.
function bundleAliases(
  config: LanguagesToml,
  parserIds: string[],
  plaintextAliases: string[],
): Record<string, string[]> {
  const aliases: Record<string, string[]> = {};

  for (const id of parserIds) {
    aliases[id] = config.parsers[id]?.aliases ?? [];
  }
  aliases["plaintext"] = plaintextAliases;

  return aliases;
}

// Every bundle carries plaintext, whether or not it names it.
function bundleLanguageIds(parserIds: string[]): string[] {
  const allIds = [...parserIds];
  if (!allIds.includes("plaintext")) allIds.push("plaintext");
  return allIds;
}

function bundleModule(allIds: string[], aliases: Record<string, string[]>): string {
  const entries = allIds
    .map((id) => {
      const a = JSON.stringify(aliases[id] ?? []);
      return `  ${JSON.stringify(id)}: lazy(${JSON.stringify(id)}, ${a}, () => import("../langs/${id}.js")),`;
    })
    .join("\n");

  return `// Auto-generated by scripts/build-langs.ts — do not edit manually.
import type { LanguageBundle } from '../src/types.js'
import { lazy } from '../src/bundle-helpers.js'

export const bundledLanguages: LanguageBundle = {
${entries}
}
`;
}

function main() {
  const config = readLanguagesToml();
  const plaintextAliases = ["text", "txt", "plain"];

  writeLanguageFiles(config, plaintextAliases);
  writeLanguageMetadata(
    collectLanguageEntries(config, plaintextAliases),
    languagePackageVersionRange(),
  );
  writeLanguageLoaders(config);
  writeThemeMetadata();
  writeBundles(config, plaintextAliases);
}

function titlecase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

main();
// Only bundles/ is committed; langs/ and src/generated are gitignored build output.
execFileSync("oxfmt", [BUNDLES_DIR], { stdio: "inherit" });
