/**
 * Generates the inline tree-sitter runtime WASM module used by
 * src/languages.ts. This embeds the web-tree-sitter parser runtime
 * as a base64-encoded TypeScript module.
 */

import fs from "node:fs";
import path from "node:path";
import { buildTreeSitterBinding } from "./build-tree-sitter-binding.mjs";

function main() {
  const wasmCandidates = [
    path.resolve(import.meta.dirname, "../node_modules/web-tree-sitter/web-tree-sitter.wasm"),
    path.resolve(import.meta.dirname, "../node_modules/web-tree-sitter/tree-sitter.wasm"),
  ];
  const treeSitterWasm = wasmCandidates.find((candidate) => fs.existsSync(candidate));

  if (treeSitterWasm) {
    const wasmBytes = fs.readFileSync(treeSitterWasm);
    const base64 = wasmBytes.toString("base64");
    const size = (wasmBytes.length / 1024).toFixed(0);

    const moduleSource = [
      "// Generated by build-runtime-wasm.ts — do not edit",
      `const wasmBase64 = "${base64}"`,
      "const wasmBinary = Uint8Array.from(atob(wasmBase64), c => c.charCodeAt(0))",
      "export default wasmBinary.buffer",
      "",
    ].join("\n");

    const outPath = path.resolve(import.meta.dirname, "../src/tree-sitter-wasm.ts");
    fs.writeFileSync(outPath, moduleSource);
    console.log(
      `  tree-sitter-wasm.ts (${size} KB WASM → ${(base64.length / 1024).toFixed(0)} KB base64)`,
    );
  } else {
    console.warn("  WARNING: runtime WASM not found in web-tree-sitter package");
  }
}

main();
await buildTreeSitterBinding();
